development:
  adapter: mysql2
  encoding: utf8
  database: mealplan_dev
  pool: 5
  username: 
  password:

test: &TEST
  adapter: mysql2
  encoding: utf8
  database: mealplan_test
  pool: 5
  username: 
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: mealplan_prod
  pool: 5
  username: 
  password: